#!/usr/bin/bash

current=$(echo '{ "command": ["get_property", "playlist-pos"] }' | socat - /tmp/mpvsocket | jq .data)
count=$(echo '{ "command": ["get_property", "playlist/count"] }' | socat - /tmp/mpvsocket | jq .data)

next=$((current+1))
target=$((count-1))

echo "{ \"command\": [\"playlist-move\", \"$target\", \"$next\"] }" | socat - /tmp/mpvsocket
echo "Moved entry: $target to positon $next"
