#!/usr/bin/bash

url="$1"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

./append "$url"
./move-last-to-current
echo "{ \"command\": [\"playlist-prev\"] }" | socat - /tmp/mpvsocket
