#!/bin/sh
#
# As of 0.13, xmonad --recompile will look for a custom build script.

set -e

stack build :my-xmonad --verbosity warn
stack install :my-xmonad --local-bin-path bin/ --verbosity warn
mv bin/my-xmonad "$1"
