#!/bin/bash

NSINKS=$(pactl list sinks short | wc -l)
if [ "$NSINKS" -gt "1" ]; then
    DEFAULT_SINK=$(pactl list sinks short | grep RUNNING | awk '{print $1}')
else
    DEFAULT_SINK=$(pactl list sinks short | awk '{print $1}')
fi

SINK=${3:-$DEFAULT_SINK}

function current {
    pactl list sinks | \
        perl -000ne "if(/#$SINK/ && /State: RUNNING/){/(Volume:.*)/; print \"\$1\n\"}" | \
        sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
}

op="$1"
case $op in
    "up")
    if [ "`current`" -lt "100" ]; then
        pactl set-sink-mute $SINK false; pactl set-sink-volume $SINK +5%
    fi
    current
    ;;
    "down")
    if [ "`current`" -gt "0" ]; then
        pactl set-sink-mute $SINK false; pactl set-sink-volume $SINK -5%
    fi
    current
    ;;
    "toggle")
    pactl set-sink-mute $SINK toggle
    ;;
    "current")
    current
    ;;
    "set")
    pactl set-sink-mute $SINK false; pactl set-sink-volume $SINK $2
    ;;
esac
